### ISSUE TITLE
Not an issue, need suggestion 

### ISSUE THREAD

**Issue by amitdotagarwal** [zhandao/zero-rails_openapi#54]
Currently, we have configured response as a static code, and whenever we do amendment in our code, we have to do change in the response part as well, can we set response as dynamic, instead of static?

Could you please let me know, how we can set response dynamic in docs.

```
api :show, 'GET the specified user' do #, builder: :show#, use: id
    query 'id', Integer  #, range: { ge: 1 }, default: 1
    response 200, :success, 'application/vnd.api+json', data: { data: [{id: 1}] }    
  end
```

**Comment by zhandao** [comment]
Do you mean to automatically generate docs based on the code in controller and view?

I have no idea about this magic, in order to implement it, it may be necessary to implement a set of DSLs to make architectural changes to Rails.

But you can also use the `dry` method to reduce the duplication of your document code work.

**Comment by amitdotagarwal** [comment]
No, only for the response section 
So, for example, If I want to display response in the json file, then will have to use 'response' method and then have to mention manually response parameter, can we use "$ref" kind of methods to define response? and how to implement this?

**Comment by zhandao** [comment]
You mean [`Reference Object`](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#referenceObject)?

**Comment by amitdotagarwal** [comment]
yes

**Comment by zhandao** [comment]
Use `response_ref` to define a Ref Obj, and `body_ref` to ref a ref obj.
